In [ ]:
import pandas as pd
df=pd.read_csv("raw_data.csv")
df.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [5]:
df.groupby("country")["income"].min()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [6]:
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:
df.groupby("gender")["income"].agg(Avg_mean="mean",min="min",max="max")

             Avg_mean      min      max
gender
Female   65666.666667  62000.0  73000.0
Male     54800.000000  45000.0  68000.0
Unknown  47000.000000  47000.0  47000.0

In [9]:
df.groupby("country").agg(
    {
        "income":"mean",
        "age":"max"
    }
)

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  31.0

In [13]:
df.groupby("country").agg(
        avg_income=("income","mean"),
        avg_age=("age","max")
)

         avg_income  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     31.0